format = """
$username\
$hostname\
$directory\
$git_branch\
$aws\
$shell\
$fill\
$nodejs\
$php\
$docker_context\
$cmd_duration $jobs $time\
$line_break\
$character"""

# Command Timeout (for PHP)
command_timeout = 1000

[shell]
zsh_indicator = "ï£¿"
bash_indicator = "ï£¿"
unknown_indicator = "mystery shell"
style = "cyan bold"
disabled = false


[nodejs]
format = "[$symbol($version )]($style)"

[docker_context]
format = "[$symbol$context]($style) "
symbol = "ğŸ³ "
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
disabled = false

[battery]
format = "[$symbol$percentage]($style) "

[fill]
symbol = " "

[aws]
symbol = "â˜ï¸ "
format = '[$symbol($profile ) (\($region\) )(\[$duration\] )]($style)'
style = "bold yellow"

[directory]
style = "blue"
read_only = "ğŸ”’"
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vicmd_symbol = "[â®](green)"

[php]
symbol = "ğŸ˜ "
format = "[$symbol($version )]($style)"

[git_branch]
symbol = "ï˜ "
format = "[$symbol$branch]($style) "

[jobs]
symbol = "âœ¦"
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
symbol = "ğŸ"

[time]
disabled = false
style = "bold white"